### ISSUE TITLE
Morph-o-Tool breaks, when there is a Wrench, that takes damage.

### ISSUE THREAD

**Issue by Aroma1997** [Vazkii/Morph-o-Tool#22]
If you have a wrench in your Morph-o-Tool, that gets damaged, when you use it and eventually breaks, then you lose your Morph-o-Tool and all the other wrenches you have in there.
An example is the IC2 Bronze Wrench. It takes damage, when you use it and eventually breaks.
To solve that problem, you could set the damage of a tool to 0 every time it is used, however that may cause balance issues.

**Comment by khionu** [comment]
I was able to reproduce this issue with 1.2-21 using the Immersive Engineering Hammer

**Comment by DoomRater** [comment]
I can also reproduce with items that are not wrenches, including the Glass Sword from Twilight Forest and occasionally the hammers from Ex Nihilio Creatio.  These events occur when the tool is used as a weapon instead of as a tool- if I use the hammer to break a block, the morph-o-tool is returned, but if I smack a slime with it, snap.

The Immersive Engineering Hammer is probably being used in a crafting recipe, causing it damage there.

**Comment by osirisgothra** [comment]
yes i noticed this too, quite annoying ( engineers hammer, I.E. ) Shouldn't it just delete the tool?

**Comment by DoomRater** [comment]
The way this seems to work is an event will fire when the item breaks.  This event with IE hammers and swords is different from the event that tools use when they break, and because of this it's harder to catch and ensure that the tool is returned without the broken item inside.  To be honest I don't know if IE hammers have the appropriate event or not.
